name: Build And Push Kwik Nesta Worker Service Docker Image To Docker Hub

on:
  pull_request:
    branches:
      - develop
    types:
      - closed

jobs:
  if_merged:
    if: github.event.pull_request.merged
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Get latest semver tag from Docker Hub
        id: get_latest_tag
        run: |
          tags=$(curl -s "https://hub.docker.com/v2/repositories/${{ secrets.HUB_USERNAME }}/kwik-nesta.workers.svc/tags?page_size=100" | jq -r '.results[].name')
          echo "All tags: $tags"

          latest_version=$(echo "$tags" | grep -E '^test-v[0-9]+\.[0-9]+\.[0-9]+$' | sort -V | tail -n 1)
          echo "Latest version: $latest_version"

          if [ -z "$latest_version" ]; then
            next_version="test-v1.0.0"
          else
            version=${latest_version#test-v}
            IFS='.' read -r major minor patch <<< "$version"

            patch=$((patch + 1))

            if [ "$patch" -ge 10 ]; then
              patch=0
              minor=$((minor + 1))
            fi

            if [ "$minor" -ge 10 ]; then
              minor=0
              major=$((major + 1))
            fi

            next_version="test-v${major}.${minor}.${patch}"
          fi

          echo "Next version: $next_version"
          echo "tag=$next_version" >> $GITHUB_OUTPUT

      - name: Build Docker Image with version and test tags
        run: |
          docker build \
            --build-arg VERSION_TAG=${{ steps.get_latest_tag.outputs.tag }} \
            --build-arg BUILD_CONFIGURATION=Release \
            -t ${{ secrets.HUB_USERNAME }}/kwik-nesta.workers.svc:${{ steps.get_latest_tag.outputs.tag }} \
            -t ${{ secrets.HUB_USERNAME }}/kwik-nesta.workers.svc:test \
            -f src/KwikNesta.Workers.Svc.Core/Dockerfile .

      - name: Push Docker Images to Docker Hub
        run: |
          docker login -u ${{ secrets.HUB_USERNAME }} -p ${{ secrets.HUB_TEST_SECRET }}
          docker push ${{ secrets.HUB_USERNAME }}/kwik-nesta.workers.svc:${{ steps.get_latest_tag.outputs.tag }}
          docker push ${{ secrets.HUB_USERNAME }}/kwik-nesta.workers.svc:test